######################################################################
##
## Filename: processor_tb.udo
## Created on: Sat Oct 05 14:14:43 Romance Daylight Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
