######################################################################
##
## Filename: processor_tb.udo
## Created on: Tue Oct 01 10:35:52 Romance Daylight Time 2013
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
